name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy using Username $ Password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PRIVATE_KEY }}
        port: 22
        sync: true
        script: |
          cd ~/apps/Challenge-11-Backend \
          && git reset --hard \
          && git pull origin main \
          && export NVM_DIR=~/.nvm \
          && source ~/.nvm/nvm.sh \
          && npm install --only=prod \
          && npm test \
          && pm2 restart ecosystem.config.js \
          && pm2 restart CH11Backend \
